### PR TITLE
[ISSUE-27] Chain-status tool usage documentation

### PR DESCRIPTION
**Pull request by lampajr**
**Thank you for submitting this pull request**

fix:
- https://github.com/kiegroup/chain-status/issues/27
- https://github.com/kiegroup/chain-status/issues/28

**referenced Pull Requests**: 
- https://github.com/kiegroup/chain-status/pull/31
- https://github.com/kiegroup/chain-status/pull/34

Added a brief documentation on how to use this tool in custom projects.

### CODE REVIEW

**Review by Ginxo — CHANGES_REQUESTED** [review]
please check my comments. Please add `Working example` at the beginning of the documentation pointing to the one from kiegroup, this way it will be easier to have a clearer view of what this tool is, wdyt?

**Comment by lampajr** [comment]
> please check my comments. Please add `Working example` at the beginning of the documentation pointing to the one from kiegroup, this way it will be easier to have a clearer view of what this tool is, wdyt?

I agree on the example, wdyt if I also add https://github.com/lampajr/chain-status-example/ this one (as a very simple external project)?  Where maybe I could also add another configuration using the list of projects (when https://github.com/kiegroup/chain-status/issues/33 will be completed)

**Comment by Ginxo** [comment]
> > please check my comments. Please add `Working example` at the beginning of the documentation pointing to the one from kiegroup, this way it will be easier to have a clearer view of what this tool is, wdyt?
> 
> I agree on the example, wdyt if I also add https://github.com/lampajr/chain-status-example/ this one (as a very simple external project)? Where maybe I could also add another configuration using the list of projects (when #33 will be completed)

@lampajr I agree

**Review by Ginxo — APPROVED** [review]
LGTM

**Review by rgdoliveira — APPROVED** [review]

**Pull request merged**
