### PR TITLE
[ISSUE-39] fix recursive listBranches

### PR DESCRIPTION
**Pull request by lampajr**
**Thank you for submitting this pull request**

fix:
- https://github.com/kiegroup/chain-status/issues/39

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM, just cover the method by unit test please. We will Boy Scout Rule principle [1] here 

[1] _leave the campground cleaner than you found it_

**Comment by lampajr** [comment]
I agree, I have already covered it a little bit in https://github.com/kiegroup/chain-status/pull/37 (that's why I did not add it here) - I will improve it there by testing the recursive part if you agree.

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by Ginxo** [comment]
@lampajr can you please resolve conflicts by generating index.js file again? Thanks

**Comment by lampajr** [comment]
@Ginxo rebased and conflicts resolved

**Pull request merged**
