### PR TITLE
Trying to upgrade @kie/build-chain-configuration-reader to v3

### PR DESCRIPTION
**Pull request by mareknovotny**
fix data page generation in https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2522#issuecomment-2472749861

### CODE REVIEW

**Review by Ginxo — APPROVED** [review]
LGTM! thanks @mareknovotny !

**Comment by mareknovotny** [comment]
it looks like versio 3 removed some function/method

`TypeError: getBaseMappingInfo is not a function`

Any advice what is the successor? @lampajr @shubhbapna

**Comment by lampajr** [comment]
> ok, found the refactoring PR which required to change also those calls here [kiegroup/build-chain-configuration-reader#47](https://github.com/kiegroup/build-chain-configuration-reader/pull/47)

I completely forgot about that refactoring 😞

**Review by lampajr — APPROVED** [review]
>@lampajr hopefully the change i found is the minimal one and still works as before, at least the tests pass locally even i needed also upgraded @vercel/ncc dev dep as it failed with
Error: error:0308010C:digital envelope routines::unsupported in hook for pre:commit

I think we can merge it and give it a try 🤞🏻

**Comment by mareknovotny** [comment]
launched this https://github.com/kiegroup/droolsjbpm-build-bootstrap/actions/runs/11837982775

**Comment by lampajr** [comment]
> launched this https://github.com/kiegroup/droolsjbpm-build-bootstrap/actions/runs/11837982775

Looks working!!!

**Comment by Ginxo** [comment]
congrats @mareknovotny ! good effort!

**Pull request merged**
