### PR TITLE
[KIEGROUP/CHAIN-STATUS] Fix ISSUE-48: some entries are not shown on t…

### PR DESCRIPTION
**Pull request by bacciotti**

### CODE REVIEW

**Review by shubhbapna — CHANGES_REQUESTED** [review]
Not sure if this has already been considered but from the [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) it seems like there are 2 additional css properties that need to be set for this to work? Additionally it seems like this property is for [block-level elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) and `<a>` tag does not seem to be a part of it

**Comment by bacciotti** [comment]
Well, as I understand reading the docs we have to use those two properties just to force the overflow (we don't want to force, just to show with the "..." when the overflow occurs). @shubhbapna

**Comment by lampajr** [comment]
Hi, I tried locally and it looks like the overflow is not shown.. I think it is because of `<a>` tag (as @shubhbapna highlighted). I found this https://stackoverflow.com/questions/16660506/use-text-overflow-ellipsis-on-an-anchor-tag that it seems it answer our doubt, maybe it is worth to give it a try. 

@bacciotti maybe you can try to create a fake repo on your user to setup the chain-status and see if the fix really solve the issue

**Comment by bacciotti** [comment]
Guys, thanks for your contribution!

@shubhbapna  @lampajr 

I added more properties to test and it worked well.

Our main concern is the fixed width. There are some options I tried but it didn't work, for instance using some relatives units like percentage (%), viewport width (vw) or viewport width maxsize (vmax). I considered even use the "em" unit but I had no success too.

I tried using a span or a paragraph inside the anchor but it didn't work.

With the current change it worked well, even with fixed width. I tested on different browsers and screen sizes, locally.

What do you think, guys?

**Review by shubhbapna — APPROVED** [review]
LGTM!

**Comment by lampajr** [comment]
This approach seems to work as well.

I'm just wondering if it could help to add an overlay with the full name when it is truncated, because consider the case when we have two jobs having the same long name except for the suffix (which could be a number or whatever) - in this case we might have the issue that we don't know to which one that record is referring to.

wdyt? @shubhbapna @bacciotti

**Comment by bacciotti** [comment]
Great idea! I can try something on this.

**Comment by bacciotti** [comment]
I inserted Tooltip component to show the complete label.

The point is that I could not set it to show only when overflowed. I tried many components and scripts on the last few days but with no further success. Maybe we define it as a future implementation?

For now, I think this improvement solve the main problem of this issue.

**Comment by lampajr** [comment]
Hey @bacciotti , 

> Maybe we define it as a future implementation?

I agree with you, do you mind to create a new issue?

**Review by lampajr — APPROVED** [review]

**Review by rgdoliveira — APPROVED** [review]

**Pull request merged**
